const { defineConfig, devices } = require('@playwright/test');

module.exports = defineConfig({
  testDir: './tests',
  fullyParallel: false, // Run tests sequentially for smoke tests
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 1,
  workers: 1, // Single worker for smoke tests
  
  // Global setup - runs once before all tests EXCEPT auth and registration tests
  globalSetup: require.resolve('./tests/global-setup'),
  globalTeardown: undefined,
  
  reporter: [
    ['html', { outputFolder: 'reports/html-report', open: 'never' }],
    ['json', { outputFile: 'reports/test-results.json' }],
    ['list']
  ],
  use: {
    baseURL: process.env.BASE_URL || 'https://beta.superconstruct.io',
    trace: 'retain-on-failure',
    screenshot: 'on',
    video: 'retain-on-failure',
    actionTimeout: 15000,
    navigationTimeout: 30000,
    // Reuse saved authentication state for all tests
    storageState: '.auth/user.json',
  },

  projects: [
    // ========== GC Flow: Register -> Create Project -> Invite Members -> Accept -> Add to Project -> Members Accept -> Invite Owner -> Owner Accept -> Invite Subcontractor -> Subcontractor Accept ==========
    {
      name: 'gc-register',
      testMatch: '**/auth/beta-registration-onboarding.spec.js',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: process.env.BASE_URL || 'https://beta.superconstruct.io',
        trace: 'retain-on-failure',
        screenshot: 'on',
        video: 'retain-on-failure',
        actionTimeout: 15000,
        navigationTimeout: 30000,
        storageState: false,
      },
    },
    {
      name: 'gc-project',
      testMatch: '**/auth/beta-create-project.spec.js',
      dependencies: ['gc-register'],
      use: {
        ...devices['Desktop Chrome'],
        baseURL: process.env.BASE_URL || 'https://beta.superconstruct.io',
        trace: 'retain-on-failure',
        screenshot: 'on',
        video: 'retain-on-failure',
        actionTimeout: 15000,
        navigationTimeout: 30000,
        storageState: '.auth/gc-storage-state.json',
      },
    },
    {
      name: 'gc-invite',
      testMatch: '**/auth/gc-invite-members.spec.js',
      dependencies: ['gc-project'],
      use: {
        ...devices['Desktop Chrome'],
        baseURL: process.env.BASE_URL || 'https://beta.superconstruct.io',
        trace: 'retain-on-failure',
        screenshot: 'on',
        video: 'retain-on-failure',
        actionTimeout: 15000,
        navigationTimeout: 30000,
        storageState: '.auth/gc-storage-state.json',
      },
    },
    {
      name: 'gc-accept',
      testMatch: '**/auth/accept-invitations-gc.spec.js',
      dependencies: ['gc-invite'],
      use: {
        ...devices['Desktop Chrome'],
        baseURL: process.env.BASE_URL || 'https://beta.superconstruct.io',
        trace: 'retain-on-failure',
        screenshot: 'on',
        video: 'retain-on-failure',
        actionTimeout: 15000,
        navigationTimeout: 30000,
        storageState: false,
      },
    },
    {
      name: 'gc-add-to-project',
      testMatch: '**/auth/gc-add-members-to-project.spec.js',
      dependencies: ['gc-accept'],
      use: {
        ...devices['Desktop Chrome'],
        baseURL: process.env.BASE_URL || 'https://beta.superconstruct.io',
        trace: 'retain-on-failure',
        screenshot: 'on',
        video: 'retain-on-failure',
        actionTimeout: 15000,
        navigationTimeout: 30000,
        storageState: '.auth/gc-storage-state.json',
      },
    },
    {
      name: 'gc-members-accept-project',
      testMatch: '**/auth/members-accept-project.spec.js',
      dependencies: ['gc-add-to-project'],
      use: {
        ...devices['Desktop Chrome'],
        baseURL: process.env.BASE_URL || 'https://beta.superconstruct.io',
        trace: 'retain-on-failure',
        screenshot: 'on',
        video: 'retain-on-failure',
        actionTimeout: 15000,
        navigationTimeout: 30000,
        storageState: false,
      },
    },
    {
      name: 'gc-invite-owner',
      testMatch: '**/auth/gc-invite-owner.spec.js',
      dependencies: ['gc-members-accept-project'],
      use: {
        ...devices['Desktop Chrome'],
        baseURL: process.env.BASE_URL || 'https://beta.superconstruct.io',
        trace: 'retain-on-failure',
        screenshot: 'on',
        video: 'retain-on-failure',
        actionTimeout: 15000,
        navigationTimeout: 30000,
        storageState: '.auth/gc-storage-state.json',
      },
    },
    {
      name: 'gc-owner-accept',
      testMatch: '**/auth/accept-owner-invitation.spec.js',
      dependencies: ['gc-invite-owner'],
      use: {
        ...devices['Desktop Chrome'],
        baseURL: process.env.BASE_URL || 'https://beta.superconstruct.io',
        trace: 'retain-on-failure',
        screenshot: 'on',
        video: 'retain-on-failure',
        actionTimeout: 15000,
        navigationTimeout: 30000,
        storageState: false,
      },
    },
    {
      name: 'gc-invite-subcontractor',
      testMatch: '**/auth/gc-invite-subcontractor.spec.js',
      dependencies: ['gc-owner-accept'],
      use: {
        ...devices['Desktop Chrome'],
        baseURL: process.env.BASE_URL || 'https://beta.superconstruct.io',
        trace: 'retain-on-failure',
        screenshot: 'on',
        video: 'retain-on-failure',
        actionTimeout: 15000,
        navigationTimeout: 30000,
        storageState: '.auth/gc-storage-state.json',
      },
    },
    {
      name: 'gc-subcontractor-accept',
      testMatch: '**/auth/accept-subcontractor-invitation.spec.js',
      dependencies: ['gc-invite-subcontractor'],
      use: {
        ...devices['Desktop Chrome'],
        baseURL: process.env.BASE_URL || 'https://beta.superconstruct.io',
        trace: 'retain-on-failure',
        screenshot: 'on',
        video: 'retain-on-failure',
        actionTimeout: 15000,
        navigationTimeout: 30000,
        storageState: false,
      },
    },
    // ========== SOV Flow: GC Login -> Create SOV -> Owner Login -> Approve SOV ==========
    // Run with: npm run test:sov-flow
    {
      name: 'sov-gc-login',
      testMatch: '**/modules/gc-login.spec.js',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: process.env.BASE_URL || 'https://beta.superconstruct.io',
        trace: 'retain-on-failure',
        screenshot: 'on',
        video: 'retain-on-failure',
        actionTimeout: 15000,
        navigationTimeout: 30000,
        storageState: false,
      },
    },
    {
      name: 'sov-create',
      testMatch: '**/modules/create-sov.spec.js',
      dependencies: ['sov-gc-login'],
      use: {
        ...devices['Desktop Chrome'],
        baseURL: process.env.BASE_URL || 'https://beta.superconstruct.io',
        trace: 'retain-on-failure',
        screenshot: 'on',
        video: 'retain-on-failure',
        actionTimeout: 15000,
        navigationTimeout: 30000,
        storageState: '.auth/gc-login-state.json',
      },
    },
    {
      name: 'sov-owner-login',
      testMatch: '**/modules/owner-login.spec.js',
      dependencies: ['sov-create'],
      use: {
        ...devices['Desktop Chrome'],
        baseURL: process.env.BASE_URL || 'https://beta.superconstruct.io',
        trace: 'retain-on-failure',
        screenshot: 'on',
        video: 'retain-on-failure',
        actionTimeout: 15000,
        navigationTimeout: 30000,
        storageState: false,
      },
    },
    {
      name: 'sov-approve',
      testMatch: '**/modules/approve-sov.spec.js',
      dependencies: ['sov-owner-login'],
      use: {
        ...devices['Desktop Chrome'],
        baseURL: process.env.BASE_URL || 'https://beta.superconstruct.io',
        trace: 'retain-on-failure',
        screenshot: 'on',
        video: 'retain-on-failure',
        actionTimeout: 15000,
        navigationTimeout: 30000,
        storageState: '.auth/owner-login-state.json',
      },
    },
  ],
});
